// <auto-generated />
using System;
using MVCTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181213055956_addUser")]
    partial class addUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCTest.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName");

                    b.Property<string>("UserPwd");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVCTest.Models.VisaForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("app_date");

                    b.Property<DateTime>("app_date_hidden");

                    b.Property<string>("app_time")
                        .IsRequired();

                    b.Property<string>("app_type");

                    b.Property<string>("captcha")
                        .IsRequired();

                    b.Property<string>("category");

                    b.Property<string>("centre");

                    b.Property<string>("countryID")
                        .IsRequired();

                    b.Property<DateTime>("dateOfBirth");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("loc_final")
                        .IsRequired();

                    b.Property<string>("loc_selected")
                        .IsRequired();

                    b.Property<string>("member")
                        .IsRequired();

                    b.Property<string>("missionId")
                        .IsRequired();

                    b.Property<string>("mission_selected")
                        .IsRequired();

                    b.Property<string>("nationalityId")
                        .IsRequired();

                    b.Property<string>("passportType")
                        .IsRequired();

                    b.Property<string>("passport_no")
                        .IsRequired();

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("phone_code");

                    b.Property<DateTime>("pptExpiryDate");

                    b.Property<DateTime>("pptIssueDate");

                    b.Property<string>("pptIssuePalace")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("VisaForm");
                });
#pragma warning restore 612, 618
        }
    }
}
